# This file intentionally left blank
SERIAL_DRIVER = vendor
VIRTSER_ENABLE = no
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3743A
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash