#pragma once

#include "quantum.h"
#include "pointing_device.h"
#include "kweboakye.h"

#define CIRQUE_TRACKPAD_X_BOUNDARY_AREA_SIZE (CIRQUE_PINNACLE_X_RANGE / 4)
#define CIRQUE_TRACKPAD_Y_BOUNDARY_AREA_SIZE (CIRQUE_PINNACLE_Y_RANGE / 4)
#define CIRQUE_TRACKPAD_RIGHT_CLICK_X_AXIS_BOUNDARY_LEFT (CIRQUE_PINNACLE_X_LOWER + CIRQUE_TRACKPAD_X_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_RIGHT_CLICK_X_AXIS_BOUNDARY_RIGHT (CIRQUE_PINNACLE_X_UPPER - CIRQUE_TRACKPAD_X_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_RIGHT_CLICK_Y_AXIS_BOUNDARY (CIRQUE_PINNACLE_Y_UPPER - CIRQUE_TRACKPAD_Y_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_RIGHT_CLICK_Y_AXIS_BOUNDARY_LEFT (CIRQUE_PINNACLE_Y_LOWER + CIRQUE_TRACKPAD_Y_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_X_AXIS_UPPER_BOUNDARY (CIRQUE_PINNACLE_X_UPPER - CIRQUE_TRACKPAD_X_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_X_AXIS_LOWER_BOUNDARY (CIRQUE_PINNACLE_X_LOWER + CIRQUE_TRACKPAD_X_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_Y_AXIS_UPPER_BOUNDARY (CIRQUE_PINNACLE_Y_UPPER - CIRQUE_TRACKPAD_Y_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD_Y_AXIS_LOWER_BOUNDARY (CIRQUE_PINNACLE_Y_LOWER + CIRQUE_TRACKPAD_Y_BOUNDARY_AREA_SIZE)
#define CIRQUE_TRACKPAD__X_AXIS_UPPER_BOUNDARY
#define CIRQUE_TRACKPAD_RIGHT_HAND_X_AXIS_LOWER_BOUNDARY
#define CIRQUE_TRACKPAD_RIGHT_HAND_Y_AXIS_UPPER_BOUNDARY
#define CIRQUE_TRACKPAD_RIGHT_HAND_Y_AXIS_LOWER_BOUNDARY




typedef enum {
    CIRQUE_TRACKPAD_TRACKPAD_MODE = 0,
    CIRQUE_TRACKPAD_SCROLLING_MODE,
    CIRQUE_TRACKPAD_CARET_MODE,
    CIRQUE_TRACKPAD_DRAG_MOM_MODE,
    CIRQUE_TRACKPAD_MODE_LAST  // Do not use, except for looping through enum values
} cirque_trackpad_mode_t;

cirque_trackpad_mode_t cirque_trackpad_mode;

cirque_trackpad_mode_t cirque_trackpad_mode_get(void) ;

void cirque_trackpad_logic_init (void);


report_mouse_t cirque_trackpad_pointing_device_task(report_mouse_t mouse_report);
process_record_result_t process_record_trackpad(uint16_t keycode, keyrecord_t* record);
