#pragma once

#define I2C_DRIVER        I2CD1
#define I2C1_SCL_PIN      B8
#define I2C1_SCL_PAL_MODE 4
#define  I2C1_SDA_PIN     B9
#define I2C1_SDA_PAL_MODE 4
#define I2C1_CLOCK_SPEED  400000
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2
#define IQS55XX_RDY_PIN B7
#define MOUSE_EXTENDED_REPORT
