#pragma once

#define SPLIT_POINTING_ENABLE 
#undef  POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_COMBINED
//#define POINTING_DEVICE_LEFT

#define MOUSE_EXTENDED_REPORT
//#define POINTING_DEVICE_COMBINED
#define CIRQUE_PINNACLE_SPI_CS_PIN POINTING_DEVICE_CS_PIN
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
#define CIRQUE_PINNACLE_TAPPING_TERM 200
#define CIRQUE_PINNACLE_TOUCH_DEBOUNCE (CIRQUE_PINNACLE_TAPPING_TERM * 8)
#define CIRQUE_PINNACLE_TIMEOUT 200
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X
#define CIRQUE_TRACKPAD_ROTATE_CLOCKWISE_90
#define CIRQUE_PINNACLE_SPI_LSBFIRST false
#define CIRQUE_PINNACLE_SPI_MODE 1
#define CIRQUE_PINNACLE_SPI_DIVISOR 64
#define CIRQUE_PINNACLE_CLOCK_SPEED 10000000

#define AZOTEQ_IQS5XX_TPS43
#define AZOTEQ_IQS5XX_TAP_ENABLE true
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
#define AZOTEQ_IQS5XX_ZOOM_ENABLE true
#define AZOTEQ_IQS5XX_SWIPE_X_ENABLE true
#define AZOTEQ_IQS5XX_TWO_FINGER_TAP_ENABLE true
#define AZOTEQ_IQS5XX_SCROLL_INITIAL_DISTANCE 15
#define AZOTEQ_IQS5XX_SCROLL_ENABLE true
#define AZOTEQ_IQS5XX_ROTATION_270
#define I2C_DRIVER        I2CD1
#define I2C1_SCL_PIN      GP2
//#define I2C1_SCL_PAL_MODE 3
#define  I2C1_SDA_PIN     GP3
//#define I2C1_SDA_PAL_MODE 3
//#undef I2C1_DUTY_CYCLE 
//#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2
#define POINTING_DEVICE_DEBUG true
#ifdef QUANTUM_PAINTER_ENABLE 
#define LCD_RST_PIN GP11
#define LCD_DC_PIN GP12
#define LCD_CS_PIN GP13
#define QP_LVGL_TASK_PERIOD 50
#define LCD_DISPLAY_ROTATION QP_ROTATION_270
#define ST7789_135
//#define ST7789_NUM_DEVICES 2

#endif


#ifdef HAPTIC_ENABLE
    #define VL91022
#endif

#ifdef BACKLIGHT_ENABLE
    #define BACKLIGHT_PIN GP15
    #define BACKLIGHT_LEVELS 5
    #define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B
    #define BACKLIGHT_PWM_DRIVER 	PWMD7
    #define BACKLIGHT_DEFAULT_LEVEL 0
    
#else 
    #define LCD_BACKLIGHT_PIN GP15
#endif
//#define VL91022