
OS_DETECTION_ENABLE = yes
UNICODEMAP_ENABLE = yes
SWAP_HANDS_ENABLE = yes
CIRQUE_ENABLED = yes
CIRQUE_ENABLED_SPI = yes
#IQS5XX_ENABLED = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
QUANTUM_LIB_SRC += i2c_master.c
CONSOLE_ENABLE = yes
OLED_ENABLE = no
WPM_ENABLE = yes
ENCODER_ENABLE	= no
TRI_LAYER_ENABLE = no		# Tri Layers
#CUSTOM_SPLIT_TRANSPORT_SYNC = yes
HAPTIC_ENABLE = no

HAPTIC_DRIVER = drv2605l
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
SRC += drivers/sensors/azoteq_iqs5xx.c
