#pragma once


#define SPI_DRIVER SPID1
#define SPI_SCK_PIN C7//GP14
#define SPI_MISO_PIN B7 //GP12
#define SPI_MOSI_PIN F1//GP15

#define LCD_CS_PIN D5 //GP13
#define LCD_DC_PIN F4 //GP29 ENCA
#define LCD_RST_PIN F5 //GP28 ENCB
#define IQS55XX_RDY_PIN  F0 // GP16

#define BACKLIGHT_PIN B5 // GP9 / Audio
#define BACKLIGHT_PWM_DRIVER PWMD4
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#define BACKLIGHT_PAL_MODE 4
#define BACKLIGHT_GPT_DRIVER GPTD4